require("dotenv").config();
const express=require("express"),cors=require("cors"),path=require("path"),fs=require("fs");
const multer=require("multer"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),QRCode=require("qrcode");
const Database=require("better-sqlite3"),{v4:uuid}=require("uuid");
const app=express(),PORT=process.env.PORT||3000,APP_URL=process.env.APP_URL||`http://localhost:${PORT}`;
const DATA=path.join(__dirname,"data"),UP=path.join(__dirname,"uploads");fs.mkdirSync(DATA,{recursive:true});fs.mkdirSync(UP,{recursive:true});
const db=new Database(path.join(DATA,"app.db"));db.pragma("journal_mode=WAL");
db.exec(`CREATE TABLE IF NOT EXISTS tenants(id TEXT PRIMARY KEY,name TEXT,slug TEXT UNIQUE,logo_url TEXT,address TEXT,phone TEXT,whatsapp TEXT,email TEXT,gstin TEXT,upi_id TEXT,currency TEXT DEFAULT 'INR',active INTEGER DEFAULT 1,created_at TEXT);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,tenant_id TEXT,name TEXT,email TEXT UNIQUE,password_hash TEXT,role TEXT,active INTEGER DEFAULT 1,created_at TEXT);
CREATE TABLE IF NOT EXISTS settings(tenant_id TEXT PRIMARY KEY,bw_price REAL DEFAULT 5,color_price REAL DEFAULT 10,a4_price REAL DEFAULT 5,a3_price REAL DEFAULT 10,photo_price REAL DEFAULT 20,auto_print INTEGER DEFAULT 1,default_printer TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,tenant_id TEXT,order_no TEXT,original_name TEXT,file_name TEXT,mime_type TEXT,copies INTEGER,print_type TEXT,paper_size TEXT,amount REAL,status TEXT,payment_mode TEXT,payment_id TEXT,created_at TEXT,paid_at TEXT);
CREATE TABLE IF NOT EXISTS printers(id TEXT PRIMARY KEY,tenant_id TEXT,name TEXT,printer_name TEXT,type TEXT,active INTEGER DEFAULT 1,last_seen TEXT);
CREATE TABLE IF NOT EXISTS print_jobs(id TEXT PRIMARY KEY,order_id TEXT,printer_id TEXT,status TEXT,attempts INTEGER DEFAULT 0,error TEXT,created_at TEXT,completed_at TEXT);
CREATE INDEX IF NOT EXISTS oi ON orders(tenant_id,status);`);
const now=()=>new Date().toISOString(),secret=()=>process.env.JWT_SECRET||"dev-secret";
const slugify=s=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,45);
function token(u){return jwt.sign({id:u.id,tenant_id:u.tenant_id,role:u.role},secret(),{expiresIn:"12h"})}
function auth(req,res,next){try{let h=req.headers.authorization||"";req.user=jwt.verify(h.replace("Bearer ",""),secret());next()}catch(e){res.status(401).json({error:"Login required"})}}
function tid(req){return req.user.role==="SUPERADMIN"?req.query.tenant_id:req.user.tenant_id}
const storage=multer.diskStorage({destination:(_,__,cb)=>cb(null,UP),filename:(_,f,cb)=>cb(null,Date.now()+"-"+uuid()+path.extname(f.originalname).toLowerCase())});
const upload=multer({storage,limits:{fileSize:(+process.env.UPLOAD_MAX_MB||15)*1024*1024},fileFilter:(_,f,cb)=>cb(null,["image/jpeg","image/png","image/webp","application/pdf"].includes(f.mimetype))});
app.use(cors());app.use(express.json());app.use("/uploads",express.static(UP));app.use(express.static(path.join(__dirname,"public")));
const se=process.env.SUPERADMIN_EMAIL||"admin@example.com";
if(!db.prepare("SELECT id FROM users WHERE email=?").get(se))db.prepare("INSERT INTO users VALUES(?,?,?,?,?,?,?,?)").run(uuid(),null,"Super Admin",se,bcrypt.hashSync(process.env.SUPERADMIN_PASSWORD||"ChangeMe123!",12),"SUPERADMIN",1,now());

app.post("/api/auth/login",(q,s)=>{let u=db.prepare("SELECT * FROM users WHERE email=? AND active=1").get(q.body.email);if(!u||!bcrypt.compareSync(q.body.password||"",u.password_hash))return s.status(401).json({error:"Invalid credentials"});s.json({token:token(u),user:{id:u.id,name:u.name,email:u.email,role:u.role,tenant_id:u.tenant_id}})});
app.get("/api/me",auth,(q,s)=>s.json({user:db.prepare("SELECT id,name,email,role,tenant_id FROM users WHERE id=?").get(q.user.id),tenant:q.user.tenant_id?db.prepare("SELECT * FROM tenants WHERE id=?").get(q.user.tenant_id):null}));

app.post("/api/admin/tenants",auth,(q,s)=>{if(q.user.role!=="SUPERADMIN")return s.status(403).json({error:"Super admin only"});let{name,email,password}=q.body;if(!name||!email||!password)return s.status(400).json({error:"Name,email,password required"});let sl=slugify(q.body.slug||name),base=sl,i=1;while(db.prepare("SELECT id FROM tenants WHERE slug=?").get(sl))sl=base+"-"+i++;let t=uuid(),u=uuid();try{db.transaction(()=>{db.prepare("INSERT INTO tenants VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(t,name,sl,"","","","",email,"","","","INR",1,now());db.prepare("INSERT INTO settings VALUES(?,?,?,?,?,?,?,?)").run(t,5,10,5,10,20,1,"");db.prepare("INSERT INTO users VALUES(?,?,?,?,?,?,?,?)").run(u,t,name,email,bcrypt.hashSync(password,12),"OWNER",1,now())})()}catch(e){return s.status(400).json({error:"Email already exists"})}s.json({tenant:db.prepare("SELECT * FROM tenants WHERE id=?").get(t)})});
app.get("/api/admin/tenants",auth,(q,s)=>q.user.role!=="SUPERADMIN"?s.status(403).json({error:"Super admin only"}):s.json({tenants:db.prepare("SELECT id,name,slug,email,phone,active FROM tenants ORDER BY created_at DESC").all()}));

app.get("/api/shop/:slug", (q,s)=>{let t=db.prepare("SELECT id,name,slug,logo_url,address,phone,whatsapp,email,currency,active FROM tenants WHERE slug=?").get(q.params.slug);if(!t||!t.active)return s.status(404).json({error:"Shop not found"});s.json({tenant:t,settings:db.prepare("SELECT bw_price,color_price,a4_price,a3_price,photo_price FROM settings WHERE tenant_id=?").get(t.id)})});
app.get("/api/shop/:slug/qr",async(q,s)=>{let t=db.prepare("SELECT slug FROM tenants WHERE slug=? AND active=1").get(q.params.slug);if(!t)return s.status(404).json({error:"Shop not found"});let url=`${APP_URL}/shop/${t.slug}`;s.json({url,qr:await QRCode.toDataURL(url,{width:800,margin:2})})});
app.post("/api/shop/:slug/orders",upload.single("file"),(q,s)=>{let t=db.prepare("SELECT * FROM tenants WHERE slug=? AND active=1").get(q.params.slug);if(!t)return s.status(404).json({error:"Shop not found"});if(!q.file)return s.status(400).json({error:"File required"});let x=db.prepare("SELECT * FROM settings WHERE tenant_id=?").get(t.id),c=Math.max(1,Math.min(50,+q.body.copies||1)),type=q.body.print_type==="COLOR"?"COLOR":q.body.print_type==="PHOTO"?"PHOTO":"BW",paper=q.body.paper_size==="A3"?"A3":"A4";let p=type==="PHOTO"?x.photo_price:type==="COLOR"?x.color_price:x.bw_price;if(paper==="A3")p+=Math.max(0,x.a3_price-x.a4_price);let id=uuid(),no="P"+Date.now().toString().slice(-8),amount=+(p*c).toFixed(2);db.prepare("INSERT INTO orders VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,t.id,no,q.file.originalname,q.file.filename,q.file.mimetype,c,type,paper,amount,"PAYMENT_PENDING","DEMO","",now(),null);s.json({order:{id,order_no:no,amount,status:"PAYMENT_PENDING"},payment:{mode:"DEMO"}})});
app.post("/api/orders/:id/demo-pay",(q,s)=>{let o=db.prepare("SELECT * FROM orders WHERE id=?").get(q.params.id);if(!o)return s.status(404).json({error:"Not found"});if(o.status==="PAYMENT_PENDING"){db.prepare("UPDATE orders SET status='PAID',payment_id=?,paid_at=? WHERE id=?").run("DEMO-"+Date.now(),now(),o.id);db.prepare("INSERT INTO print_jobs VALUES(?,?,?,?,?,?,?,?)").run(uuid(),o.id,null,"QUEUED",0,"",now(),null)}s.json({order:db.prepare("SELECT * FROM orders WHERE id=?").get(o.id)})});
app.get("/api/orders/:id",(q,s)=>{let o=db.prepare("SELECT order_no,amount,status,created_at,paid_at FROM orders WHERE id=?").get(q.params.id);o?s.json({order:o}):s.status(404).json({error:"Not found"})});

app.get("/api/dashboard",auth,(q,s)=>{let t=tid(q);if(!t)return s.status(400).json({error:"tenant_id required"});s.json({stats:db.prepare(`SELECT SUM(date(created_at)=date('now','localtime')) orders_today,SUM(CASE WHEN date(created_at)=date('now','localtime') AND status IN ('PAID','PRINTING','PRINTED') THEN amount ELSE 0 END) sales_today,SUM(status IN ('PAID','PRINTING')) pending,SUM(status='PRINTED') printed FROM orders WHERE tenant_id=?`).get(t)})});
app.get("/api/settings",auth,(q,s)=>{let t=tid(q);s.json({tenant:db.prepare("SELECT * FROM tenants WHERE id=?").get(t),settings:db.prepare("SELECT * FROM settings WHERE tenant_id=?").get(t)})});
app.put("/api/settings",auth,(q,s)=>{let t=tid(q),b=q.body;db.prepare("UPDATE tenants SET name=?,logo_url=?,address=?,phone=?,whatsapp=?,email=?,gstin=?,upi_id=? WHERE id=?").run(b.name,b.logo_url||"",b.address||"",b.phone||"",b.whatsapp||"",b.email||"",b.gstin||"",b.upi_id||"",t);db.prepare("UPDATE settings SET bw_price=?,color_price=?,a4_price=?,a3_price=?,photo_price=?,auto_print=?,default_printer=? WHERE tenant_id=?").run(+b.bw_price||0,+b.color_price||0,+b.a4_price||0,+b.a3_price||0,+b.photo_price||0,b.auto_print?1:0,b.default_printer||"",t);s.json({ok:true})});
app.get("/api/orders",auth,(q,s)=>s.json({orders:db.prepare("SELECT * FROM orders WHERE tenant_id=? ORDER BY created_at DESC LIMIT 200").all(tid(q))}));

app.post("/api/print-agent/claim",(q,s)=>{if(q.headers["x-print-key"]!==secret())return s.status(401).json({error:"Invalid agent key"});let j=db.prepare(`SELECT j.*,o.file_name,o.copies,o.status order_status FROM print_jobs j JOIN orders o ON o.id=j.order_id WHERE j.status='QUEUED' ORDER BY j.created_at LIMIT 1`).get();if(!j)return s.json({job:null});db.prepare("UPDATE print_jobs SET status='PRINTING',attempts=attempts+1 WHERE id=?").run(j.id);db.prepare("UPDATE orders SET status='PRINTING' WHERE id=?").run(j.order_id);s.json({job:{...j,file_url:`${APP_URL}/uploads/${j.file_name}`}})});
app.post("/api/print-agent/:id/status",(q,s)=>{if(q.headers["x-print-key"]!==secret())return s.status(401).json({error:"Invalid agent key"});let ok=q.body.status==="PRINTED",j=db.prepare("SELECT * FROM print_jobs WHERE id=?").get(q.params.id);if(!j)return s.status(404).json({error:"Job not found"});db.prepare("UPDATE print_jobs SET status=?,error=?,completed_at=? WHERE id=?").run(ok?"PRINTED":"FAILED",q.body.error||"",ok?now():null,j.id);db.prepare("UPDATE orders SET status=? WHERE id=?").run(ok?"PRINTED":"FAILED",j.order_id);s.json({ok:true})});

app.get("/shop/:slug",(q,s)=>s.sendFile(path.join(__dirname,"public","shop.html")));
app.get("/admin",(q,s)=>s.sendFile(path.join(__dirname,"public","admin.html")));
app.get("/owner",(q,s)=>s.sendFile(path.join(__dirname,"public","owner.html")));
app.listen(PORT,()=>console.log("HYTECH Auto Print running on "+APP_URL));